# Generated by Django 4.1.7 on 2023-11-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
